name: sentry_gas_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  google_fonts: ^6.2.1
  pinput: ^5.0.0
  
  # --- CHANGED: Removed Bluetooth, Added QR & HTTP ---
  # flutter_blue_plus: ^1.34.5 (Removed)
  mobile_scanner: ^5.2.3  # Added for QR Code Scanning
  http: ^1.2.2            # Added for sending data to ESP8266
  
  permission_handler: ^11.3.1 
  syncfusion_flutter_gauges: ^25.2.7
  overlay_support: ^2.1.0
  flutter_animate: ^4.5.0
  simple_animations: ^5.2.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.2.3
  liquid_progress_indicator_v2: ^0.5.0
  
  # Native Splash
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

# --- App Icon Settings (Menu Icon) ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000" # Background set to Black
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# --- Splash Screen Settings (Start-up Screen) ---
flutter_native_splash:
  color: "#000000" # Splash screen background color
  image: "assets/icons/app_icon.png" # Splash screen image
  android_12:
    color: "#000000" # Android 12 splash screen background color
    image: "assets/icons/app_icon.png"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png
    - assets/icons/app_icon_foreground.png