# UPDATED: Fixed 'name' and reverted 'fl_chart'
name: sentry_gas_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  # UI
  google_fonts: ^6.2.1
  pinput: ^4.0.0
  
  # For Bluetooth
  flutter_blue_plus: ^1.31.20
  
  # For Permissions
  permission_handler: ^11.3.1 

  syncfusion_flutter_gauges: ^25.2.7
  overlay_support: ^2.1.0

  # For Firestore Database
  cloud_firestore: ^5.2.0

  flutter_animate: ^4.5.0
  simple_animations: ^5.2.0
  shared_preferences: ^2.5.3
  
  # REVERTED: Back to 0.68.0 to solve conflict
  fl_chart: 0.68.0
  flutter_local_notifications: ^17.2.1
  liquid_progress_indicator_v2: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true